### ISSUE TITLE
Unable to find << /usr/local/opt/go/libexec >>

### ISSUE THREAD

**Issue by abhi18av** [conda-forge/go-feedstock#1]
Hi `conda-forge` team

I tried to experimenting with `go` from the `conda-forge` channel but it seems that the path variables for the same are not set properly

```sh
❯ go version
go: cannot find GOROOT directory: /usr/local/opt/go/libexec
```

The `go` lang binaries seem to be have been installed properly
```sh
❯ which go
/Users/eklavya/anaconda/bin/go
```

**Comment by nehaljwani** [comment]
Are you sure you activated the environment? Activating the environment will set the GOROOT variable appropriately. 

Please share output for:
```
hash -r
which go
echo $GOROOT
go version
```

**Comment by abhi18av** [comment]
Hi @nehaljwani ,

I eventually restarted my computer and then it started working 😄 

```sh

❯ which go
/Users/eklavya/anaconda/bin/go

❯ go version
go version go1.9.1 darwin/amd64

```

It seems the `homebrew` based `go` installation was interfering with the proper settings.

**Comment by samuelarogbonlo** [comment]
> Are you sure you activated the environment? Activating the environment will set the GOROOT variable appropriately.
> 
> Please share output for:
> 
> ```
> hash -r
> which go
> echo $GOROOT
> go version
> ```

Hi @nehaljwani @abhi18av I have same issue and after following these steps, I still don't have it solved, please advice

**Comment by nehaljwani** [comment]
@samuelarogbonlo My comment asks for the output for certain commands. Please activate the conda environment, type those command and share the output so that I can help you further.

**Comment by samuelarogbonlo** [comment]
➜  axiom git:(master) ✗ hash -r 
➜  axiom git:(master) ✗ which go
/usr/local/go/bin/go
➜  axiom git:(master) ✗ echo $GOROOT

➜  axiom git:(master) ✗ go version
go version go1.16.5 darwin/amd64

**Comment by nehaljwani** [comment]
It doesn't seem like you have activated the conda environment in which you have installed go.

You need to:
```bash
conda create -n godev go -c conda-forge
conda activate godev
echo $GOROOT
which go
go version
```
