### ISSUE TITLE
Finding trouble cross-compiling darwin/amd64 -> darwin/arm64 with this package

### ISSUE THREAD

**Issue by anjos** [conda-forge/go-feedstock#132]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I'm trying to cross-compile `restic` at https://github.com/conda-forge/restic-feedstock/pull/4, at an osx-64 machine to osx-arm64.  The feedstock checks fail on the cross-compilation with:

`fork/exec /tmp/go-build3926025153/b001/exe/build: bad CPU type in executable`

I recreated the environment locally and I can reproduce this problem on my osx-64 machine.  Here are the steps:

```sh
$ conda create -n test go go-nocgo_osx-arm64 
$ conda activate test
(test) $ wget https://github.com/restic/restic/archive/v0.12.1.tar.gz
(test) $ tar xf v0.12.1.tar.gz
(test) $ cd restic-0.12.1
(test) $ go run build.go
fork/exec /var/folders/b3/7l98n3bd7dqc1stjmgxb9mbw0000gn/T/go-build2633307395/b001/exe/build: bad CPU type in executable
(test) $ unset GOARCH
(test) $ go run build.go --goarch arm64
# works flawlessly!  But why?
```

Is there a known issue that would affect this behaviour?  That is, using the environment variable causes the compiler to misbehave, whereas using the flag makes it produce the right binary.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/andre/mamba/envs/test:
#
# Name                    Version                   Build  Channel
_go_select                2.2.0                     nocgo    conda-forge
go                        1.16.9               h3b22d28_0    conda-forge
go-nocgo_osx-arm64        1.16.9               h1418d88_1    conda-forge
libcxx                    12.0.1               habf9029_0    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test
    active env location : /Users/andre/mamba/envs/test
            shell level : 2
       user config file : /Users/andre/.condarc
 populated config files : /Users/andre/mamba/.condarc
                          /Users/andre/mamba/condarc
                          /Users/andre/.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.9.7.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/andre/mamba  (writable)
      conda av data dir : /Users/andre/mamba/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://www.idiap.ch/software/bob/conda/label/beta/osx-64
                          https://www.idiap.ch/software/bob/conda/label/beta/noarch
                          https://www.idiap.ch/software/bob/conda/osx-64
                          https://www.idiap.ch/software/bob/conda/noarch
          package cache : /Users/andre/mamba/pkgs
                          /Users/andre/.conda/pkgs
       envs directories : /Users/andre/mamba/envs
                          /Users/andre/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by nehaljwani** [comment]
Are you trying to run a osx-arm64 binary on osx-64? I don't think that would work

**Comment by anjos** [comment]
@nehaljwani: That is not what I'm trying to do.  The go compiler is an osx-64 compiler installed on an osx-64 machine.  The compiler can produce an osx-arm64 binary.  This does not work if the environment variable is set, but does if we unset it and use the flag.  The generated binary is an osx-arm64 and cannot execute on the host platform, obviously.  I hope that clarifies.

**Comment by nehaljwani** [comment]
It doesn't seem anything is unexpected here. Go run is trying to build and execute for the target platform, which is expected. The --goarch flag is something that the build program is providing: https://github.com/restic/restic/blob/master/build.go#L101 . When you unset GOARCH, go automatically starts targeting the host platform, which is why it works.

Not all go projects use a build script written in go to drive their builds

**Comment by nehaljwani** [comment]
You could replace the build script invocation with this:
```
mkdir $PREFIX/bin
GO111MODULE=on go build -trimpath -tags selfupdate -ldflags -s -w -X "main.version=$PKG_VERSION" -o $PREFIX/bin
```
But I don't see any downside in using a selector: `# [target_platform=="osx-arm64"]` to unset `GOARCH` and use the CLI argument.

**Comment by anjos** [comment]
I move the build to a script and used the shell equivalent of the selector within it.  That worked alright.  Thanks for the insight.
