### ISSUE TITLE
Process of regenerating patches? 

### ISSUE THREAD

**Issue by rigzba21** [conda-forge/go-feedstock#143]
### Comment:

I've [forked+cloned a copy of the go-feedstock](https://github.com/rigzba21/go-feedstock/tree/1.18) and was trying to work on a PR for updating to go 1.18, and realized that I'm not entirely sure if I'm actually formatting the patches correctly (the most recent feedstock branch at sodre/go is [feedstock-go1.14.2](https://github.com/sodre/go/tree/feedstock-go1.14.2):

Trying to follow the ["Regenerating the patches"](https://github.com/conda-forge/go-feedstock/tree/main/recipe/patches#regenerating-the-patches) instructions:
```bash
# from within go-feedstock/recipe/patches
git clone https://github.com/sodre/go.git
cd go
git checkout feedstock-go1.14.2
git format-patch go1.14.2 -o ..
cd .. 
rm -rf go
```

Is this the right way to regenerate the patches? I realize I may not have enough context, so I'm wondering if I'm missing anything?
Thanks!

**Comment by mariusvniekerk** [comment]
yeah I've mostly been updating this one.  and haven't needed to update patches.  The general approach would be
* clone to golang sources
* checkout the appropriate tag
* apply the patches in order
  * if they don't apply
     * apply them to whatever branch they were applied on originally
     * rebase that branch onto the tag you want
* generate the updated patches as per the docs
