### ISSUE TITLE
update to Go 1.18

### ISSUE THREAD

**Issue by stevekm** [conda-forge/go-feedstock#148]
Go 1.18 is a major new release

https://go.dev/blog/go1.18

https://tip.golang.org/doc/go1.18

However, the current latest version of Go in `conda` is 1.17.8 

https://anaconda.org/conda-forge/go

Can we get this updated to 1.18?

Note that there are compatibility issues with 1.18 and old version of macOS; https://github.com/golang/go/issues/50855 ; not sure if this affects anything for updating the package in conda-forge

**Comment by hmaarrfk** [comment]
this was completed a few days ago

Once https://github.com/conda-forge/go-activation-feedstock/pull/8 is build on main, it should be ready to go.
