### ISSUE TITLE
Older packages do not have the same restrictions on the compilers

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/go-feedstock#154]
### Comment:

For a while, 1.17.8 didn't have a release for the `go-activation-feedstock`.

This caused packages that were rendered with the gcc compilers version 10 to pick up a really old version of go (1.13 or 1.11)

Should we mark these older packages as broken? or retroactively patch them to mark them as incompatible with gcc.

**Comment by nehaljwani** [comment]
If the packages were successfully built and don't have any reported issues, why mark them as broken?

**Comment by hmaarrfk** [comment]
I guess my question might be restructured in :

Why are we constraining the c compiler version in newer versions?


Marking them as broken is more an easy solution. What we should do is comstrain their compiler versions
