### ISSUE TITLE
Would it be possible to update go to 1.20 if possible?

### ISSUE THREAD

**Issue by cjwomack** [conda-forge/go-feedstock#175]
### Comment:

I was trying to install [https://github.com/janpfeifer/gonb](https://github.com/janpfeifer/gonb) but this requires Go 1.20. (I forked the repo to see whether it actually needs 1.20) and it definitely requires 1.19 as the code uses atomic.Bool as far as I understand this article [https://go101.org/article/concurrent-atomic-operation.html](https://go101.org/article/concurrent-atomic-operation.html)

***Irrelevant context stuff***
gonb is a jupyter kernel and it's useful because it can be used on Google Colab if sharing with others and also **`if`** the go version is updated on conda-forge, one can use it within a conda environment with jupyterlab....

A workaround without a go conda-forge update for working between conda jupyter lab and colab is:
* to have a go jupyter kernel in conda is to install the alternative go kernel gophernotes (which doesn't work on colab) and paste the code from the sample gonb notebook into this gophernotes .ipynb which will allow the code to execute on colab if the below instruction is followed
* On colab, then comment out //`package main` and //`main()` for the gonb kernel to function
* If switching back to your conda environment with the gophernotes environment installed (as no 1.20 go), then do the reverse, uncomment `package main` and `main()`

Sorry, if this sounds confusing (I was playing around between colab and my PC)

Of course, one could always not do the conda environment thing...

Sorry, I don't know how to create a conda package and am a newbie to go.

**Comment by xhochy** [comment]
Released.
