### ISSUE TITLE
Problem downloading latest go

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/go-feedstock#25]
Saw the rather unusual error when downloading `go`. Seems to be reproducible.

```
conda.CondaMultiError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/linux-64/go-1.10.3-hfc679d8_2.tar.bz2'.
  download saved to: /opt/conda/pkgs/go-1.10.3-hfc679d8_2.tar.bz2
  expected md5 sum: d1200c158bc4d7913123a867858b36f6
  actual md5 sum: 2306a66b079aa2bfd2ea37b8c90e0694
```

ref: https://circleci.com/gh/conda-forge/gosu-feedstock/2

**Comment by sodre** [comment]
@jakirkham, I can reproduce the issue here as well. Obviously this did not show up during all the tests. 

Can you set the `broken` label to `go` in conda-forge?

**Comment by jakirkham** [comment]
Looks like someone already did, but they left the `main` label. Have fixed that now.

**Comment by sodre** [comment]
can you do the same for go-core, go_{linux,osx,win}-64 _2 as well?

**Comment by jakirkham** [comment]
Looks like someone already did.

**Comment by jakirkham** [comment]
Closing as resolved.
