### ISSUE TITLE
Defining CC and CXX causes confusion

### ISSUE THREAD

**Issue by pearu** [conda-forge/go-feedstock#47]
The `go` activate script defines `CC` and `CXX` with no real path values:
https://github.com/conda-forge/go-feedstock/blob/8b4833c2d4ca17efab0e7890e5d9fd097eb34f45/recipe/activate-go-nocgo.sh#L8

This breaks building many (non-`go`) software libraries that look for `CC` and `CXX` values to contain paths to C and C++ compilers.

If `go` needs to force the user to certain behavior, it shouldn't do that at the expense of confusion. Perhaps defining
```
export CC=
export CXX=
```
would be more appropriate?
Or use `CGO_CC`, `CGO_CXX` and leave `CC` and `CXX` alone?

**Comment by sodre** [comment]
Just install the cgo package instead. It uses the correct compiler.

**Comment by pearu** [comment]
@sodre, indeed, to install `cgo` was my first reaction and I did try that, but there seems to be no `cgo` conda package in conda-forge channel. There is `go-cgo` but replacing `go` with `go-cgo` did not clean up `CC`.

I understand your reasoning from the perspective of `go` software. But from the perspective of other software (not using `go` at all), it is confusing. In general, `CC` and `CXX` are expected to be either empty or contain paths to compiler programs. If neither is the case, then this indicates an user problem (user has specified a wrong path or similar).

As I see the situation here, the `go` package is using a `make` specific environment variable to message something to its users. This does not seem appropriate, IMHO, as it influences other projects that do not use `go`.

**Comment by pearu** [comment]
It seems that removing go packages (using `conda remove go go-cgo`) does not clean up the activation scripts in `etc/conda/arctivate.d/`. Recreating the environment w/o installing `go` might be an option.

Using the settings during `conda build` helps when building non-conda software from conda environment, so the chances of hitting this issue will be smaller indeed. On the other hand, it might make the situation worse as it is now. For instance, when debugging conda builds, I would expect that executing the `build.sh` script of some package manually (with properly set environment) would have the same result as if the `build.sh` is executed within `conda build`.

As I understand, you don't see removing
```
export CC="/use/the/cgo/conda/package/instead"
```
from activation scripts as an option but I hope you can reconsider and find a better solution because of the following:
You mentioned that the reason of invalidating `CC` content is that some `go` package build systems set `CGO_ENABLED=1` on fly. I don't know much about `go` package build conditions, but it would be useful to understand which part of the `go` ecosystem is doing something wrong and then fixing the issue at the source. Invalidating `CC` globally does sound as an easy solution for `go` ecosystem but not the proper one for a larger ecosystem that contains `go`.

**Comment by sodre** [comment]
@pearu 

> It seems that removing go packages (using `conda remove go go-cgo`) does not clean up the activation scripts in `etc/conda/arctivate.d/`. Recreating the environment w/o installing `go` might be an option.
I looked at the meta.yaml files again, the [de]activate scripts are part of the go-nocgo_{linux,osx,win}-64 packages. These are there to support cb3 `compiler` jinja tags. Those are the correct packages to remove to get rid of scripts.

> 
> Using the settings during `conda build` helps when building non-conda software from conda environment, so the chances of hitting this issue will be smaller indeed. On the other hand, it might make the situation worse as it is now. For instance, when debugging conda builds, I would expect that executing the `build.sh` script of some package manually (with properly set environment) would have the same result as if the `build.sh` is executed within `conda build`.
> 

I think the best practices now-a-days for debugging a build.sh is to actually call 'conda debug'. This creates a `build_env` and `host_env` just like it would happen if you called `conda build`. Given this new data-point, do you think the conda build option makes more sense? 

Another option, is for us not to install the go-nocgo_{linux,osx,win}-64 packages when you conda install go. This should get us closer to the previous behavior from a few builds ago. What do you think?

> As I understand, you don't see removing
> 
> ```
> export CC="/use/the/cgo/conda/package/instead"
> ```
> from activation scripts as an option but I hope you can reconsider and find a better solution because of the following:
> You mentioned that the reason of invalidating `CC` content is that some `go` package build systems set `CGO_ENABLED=1` on fly. I don't know much about `go` package build conditions, but it would be useful to understand which part of the `go` ecosystem is doing something wrong and then fixing the issue at the source. Invalidating `CC` globally does sound as an easy solution for `go` ecosystem but not the proper one for a larger ecosystem that contains `go`.

This issue is not rooted in Go itself, but instead on individual packages and the way folks setup their makefiles. For example, even though I am setting CGO_ENABLED=0 for the base cgo package, that does not stop an upstream author to set CGO_ENABLED=1. At that point, `go` will happily try to use the default compilers in the box.

**Comment by abellgithub** [comment]
I would suggest that it is incorrect for the go activation script to introduce CC and CXX at all.  Conda users may well be using go for some purpose unrelated to go development or such.  Setting CC and CXX can break other common systems (cmake, for example) that are trying to build software in an environment containing the go package.

**Comment by JoaoFelipe** [comment]
> I would suggest that it is incorrect for the go activation script to introduce CC and CXX at all. Conda users may well be using go for some purpose unrelated to go development or such. Setting CC and CXX can break other common systems (cmake, for example) that are trying to build software in an environment containing the go package.

It is exactly what just happened to me. I'm trying to reproduce jupyter notebooks (to extend this paper: http://www.ic.uff.br/~leomurta/papers/pimentel2019a.pdf) and I realized that some notebooks were calling Go. After using conda to install Go, every python package that attempted to compile C code failed to install.

**Comment by scopatz** [comment]
PRs welcome!

**Comment by sodre** [comment]
Looking back at it, I would start by splitting the compiler logic (needed by conda-build) from the base go package (used mostly by end-users)

I think I documented these as github issues before I became extremely consumed with my current day job.

**Comment by pearu** [comment]
Got hit by this issue again:
```
/home/pearu/mconda3/conda-bld/omniscidb-cuda_1570539671495/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/etc/conda/activate.d/nvcc_linux-64_activate.sh: line 46: /use/the/cgo/conda/package/instead: No such file or directory
```

**Comment by jakirkham** [comment]
@sodre, would you be open to a short term solution like what @pearu originally proposed? It sounds like the more correct solution may take more collective bandwidth than we have ATM. WDYT?

**Comment by sodre** [comment]
@jakirkham, I am basically done with the split, see conda-forge/staged-recipes#9470, conda-forge/staged-recipes#9468 and conda-forge/staged-recipes#9535. We are just missing the "compiler" packages which would include the separate activate/deactivate scripts.

**Comment by jakirkham** [comment]
Is that something you are looking for help with? If so, could you please outline what one would need to do?
