### ISSUE TITLE
Request to package `go-1.10.2`

### ISSUE THREAD

**Issue by scottt** [conda-forge/go-feedstock#51]
I have one application where the Go toolchain is updated in a very conservative manner that relies on `go-1.10.2`.

I'd really like to be able to use conda to manage the build environment setup and thus this is a request to package `go-1.10.2` in `conda-forge`.

**Comment by sodre** [comment]
@scottt, if you are wondering why we need to build from source, please take look at part of our test functions, and the fact that it is not passing for macOS for go 1.10.2. (see #52)

For you use case, will you need to build under macOS *with* CGO_ENABLED=1? If not, I can disable the cgo build for macOS to enable your use-case.

**Comment by sodre** [comment]
@scott, a build 1.10.2 is ready to merge after you confirm what was built is sufficient for you.

**Comment by scottt** [comment]
@sodre, I don't need CGO so that should indeed be sufficient.
Thanks a bunch for the quick response!

**Comment by sodre** [comment]
Cool, I merged it into 1.10.x branch, we just need to wait for the build servers to do their job.
