### ISSUE TITLE
Version 1.12

### ISSUE THREAD

**Issue by jcrist** [conda-forge/go-feedstock#53]
Go 1.12 was just released, it would be useful to me to have that available on conda-forge.

I'm willing to help if needed, though I'm not sure what all would be involved - this is a more complicated build than I'm used to dealing with.

**Comment by stuarteberg** [comment]
>I'm willing to help if needed



I've been looking at this recipe today. I haven't built this package myself, but I think it would be a matter of just updating the `version` and the `sha256` fields.  (Despite the complexity of the recipe, I don't *think* there's necessarily anything more to do, but I'm not sure.  @sodre could offer some guidance here, I think.)

>this is a more complicated build than I'm used to dealing with.

 While we're in the process of upgrading the go version, we should add some lengthy comments in `meta.yaml` to explain that this recipe is used to build different variants of the package (`go-cgo` and `go-nocgo`), explain what the `go-cgo_linux-64`, etc. packages are for, and why they aren't simply built into the main `go-[no]cgo` package, and also explain that `go`is a metapackage for `go-nocgo` and `go-nocgo_<platform>`.

**Comment by sodre** [comment]
I am happy to work on this together at AnacondaCon, if either of you are attending. In the meantime, let me try to do a quick update for 1.12.

**Comment by sodre** [comment]
the "quick" update took 5 months and the help of a lot of folks.... 

this should now be solved for Linux and OSX.

**Comment by mrocklin** [comment]
Thanks @sodre (and others) !

**Comment by Zireael** [comment]
> the "quick" update took 5 months and the help of a lot of folks....

1.13 was a mess, but hope 1.14 hits conda-forge!
