### ISSUE TITLE
Request to package nodejs-9.11.2

### ISSUE THREAD

**Issue by scottt** [conda-forge/go-feedstock#58]
Issue: I ran into an app that I need to do some maintenance on that requires `nodejs-9.11.2`.
https://nodejs.org/download/release/latest-v9.x/

**Comment by nehaljwani** [comment]
Please open an issue at https://github.com/conda-forge/nodejs-feedstock

**Comment by scottt** [comment]
My apologies for somehow getting the `node` and `go` feedstocks mixed up!
