### ISSUE TITLE
Building with go on macOS 10.14 encounters missing symbols

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/go-feedstock#59]
Ran into this issue ( https://github.com/golang/go/issues/29597 ) recently when trying to build with Go on macOS 10.14. Not entirely sure if it is an issue with the Go package, the Anaconda compilers, or if there is something I'm doing incorrectly.

**Comment by sodre** [comment]
@jakirkham, I know this was a long time ago. I would be curious if that issue is still reproducible with the current version of go (1.13.10) that is being uploaded to anaconda.org

**Comment by jakirkham** [comment]
Sorry for the lack of reply

No clue. Let's go ahead and close. We can reopen or create new issue if it resurfaces
