### ISSUE TITLE
go-cgo for osx

### ISSUE THREAD

**Issue by agcopenhaver** [conda-forge/go-feedstock#64]
is there any particular reason go-cgo is disabled for osx?

https://github.com/conda-forge/go-feedstock/blob/master/recipe/conda_build_config.yaml#L3

**Comment by scopatz** [comment]
Perhaps because it wasn't building correctly? PRs welcome, I am sure

**Comment by sodre** [comment]
closed in #65. Thanks @agcopenhaver!
