### ISSUE TITLE
Did GOOS and GOARCH get removed from env variables?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/go-feedstock#86]
My build relied on those two variables being set

https://github.com/conda-forge/zaber-motion-feedstock/pull/7

Did they go away for a good reason?

**Comment by sodre** [comment]
Yes, you can get them using go env goarch, go env goos.

It was redundant to set them and it would override the users defaults unnecessarily.

**Comment by sodre** [comment]
@hmaarrfk, if you are looking to use them in your recipes then my suggestion is to use the variants `target_gobin`, `target_goos`, `target_goarch`. They are defined in conda-forge-pinning.

**Comment by hmaarrfk** [comment]
Got it. Thanks!
